# Generated by Django 5.2 on 2025-04-19 04:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Banco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, unique=True, verbose_name='Nombre del Banco')),
                ('codigo_swift', models.CharField(blank=True, max_length=11, null=True, unique=True, verbose_name='Código SWIFT/BIC')),
                ('activo', models.BooleanField(default=True, verbose_name='¿Está Activo?')),
            ],
            options={
                'verbose_name': 'Banco',
                'verbose_name_plural': 'Bancos',
            },
        ),
        migrations.CreateModel(
            name='Entrenador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula', models.CharField(max_length=20, unique=True, verbose_name='Cédula')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre(s)')),
                ('apellido', models.CharField(max_length=100, verbose_name='Apellido(s)')),
                ('telefono', models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono')),
                ('correo_electronico', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo Electrónico')),
                ('especialidad', models.CharField(blank=True, max_length=150, null=True, verbose_name='Especialidad')),
                ('fecha_contratacion', models.DateField(blank=True, null=True, verbose_name='Fecha de Contratación')),
                ('activo', models.BooleanField(default=True, verbose_name='¿Está Activo?')),
            ],
            options={
                'verbose_name': 'Entrenador',
                'verbose_name_plural': 'Entrenadores',
            },
        ),
        migrations.CreateModel(
            name='MetodoPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Método de Pago')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('requiere_banco', models.BooleanField(default=False, verbose_name='¿Requiere Banco?')),
                ('activo', models.BooleanField(default=True, verbose_name='¿Está Activo?')),
            ],
            options={
                'verbose_name': 'Método de Pago',
                'verbose_name_plural': 'Métodos de Pago',
            },
        ),
        migrations.CreateModel(
            name='Miembro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula', models.CharField(max_length=20, unique=True, verbose_name='Cédula')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre(s)')),
                ('apellido', models.CharField(max_length=100, verbose_name='Apellido(s)')),
                ('fecha_nacimiento', models.DateField(blank=True, null=True, verbose_name='Fecha de Nacimiento')),
                ('telefono', models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono')),
                ('correo_electronico', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo Electrónico')),
                ('direccion', models.TextField(blank=True, null=True, verbose_name='Dirección')),
                ('fecha_registro', models.DateField(auto_now_add=True, verbose_name='Fecha de Registro')),
                ('id_huella', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='ID Huella Dactilar')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='fotos_miembros/', verbose_name='Foto')),
                ('condicion_medica', models.TextField(blank=True, null=True, verbose_name='Condiciones Médicas')),
                ('contacto_emergencia_nombre', models.CharField(blank=True, max_length=200, null=True, verbose_name='Nombre Contacto Emergencia')),
                ('contacto_emergencia_parentesco', models.CharField(blank=True, max_length=50, null=True, verbose_name='Parentesco Contacto Emergencia')),
                ('contacto_emergencia_telefono', models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono Contacto Emergencia')),
                ('notas', models.TextField(blank=True, null=True, verbose_name='Notas Adicionales')),
            ],
            options={
                'verbose_name': 'Miembro',
                'verbose_name_plural': 'Miembros',
            },
        ),
        migrations.CreateModel(
            name='Objetivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre del Objetivo')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Objetivo',
                'verbose_name_plural': 'Objetivos',
            },
        ),
        migrations.CreateModel(
            name='TipoClase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('color_hex', models.CharField(blank=True, max_length=7, null=True, verbose_name='Color (Hex)')),
                ('activo', models.BooleanField(default=True, verbose_name='¿Activo?')),
            ],
            options={
                'verbose_name': 'Tipo de Clase',
                'verbose_name_plural': 'Tipos de Clases',
            },
        ),
        migrations.CreateModel(
            name='TipoMembresia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, unique=True, verbose_name='Nombre del Plan')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('duracion_dias', models.PositiveIntegerField(verbose_name='Duración Estándar (días)')),
                ('precio_estandar', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio Estándar')),
                ('permite_acceso_clases', models.BooleanField(default=True, verbose_name='¿Permite Acceso a Clases?')),
                ('activo', models.BooleanField(default=True, verbose_name='¿Plan Activo?')),
            ],
            options={
                'verbose_name': 'Tipo de Membresía',
                'verbose_name_plural': 'Tipos de Membresía',
            },
        ),
        migrations.CreateModel(
            name='Membresia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField(verbose_name='Fecha de Inicio')),
                ('fecha_vencimiento', models.DateField(verbose_name='Fecha de Vencimiento')),
                ('precio_pagado', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio Acordado/Pagado')),
                ('fecha_compra', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Compra/Registro')),
                ('activa', models.BooleanField(default=True, verbose_name='¿Membresía Activa?')),
                ('estado_pago', models.CharField(choices=[('Pendiente', 'Pendiente'), ('Parcial', 'Pagado Parcialmente'), ('Pagado', 'Pagado Totalmente')], default='Pendiente', max_length=10, verbose_name='Estado del Pago')),
                ('miembro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_gimnasio.miembro', verbose_name='Miembro')),
                ('tipo_membresia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app_gimnasio.tipomembresia', verbose_name='Tipo de Membresía')),
            ],
            options={
                'verbose_name': 'Membresía',
                'verbose_name_plural': 'Membresías',
            },
        ),
        migrations.AddField(
            model_name='miembro',
            name='objetivos',
            field=models.ManyToManyField(blank=True, to='app_gimnasio.objetivo', verbose_name='Objetivos'),
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_pago', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y Hora del Pago')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto Pagado')),
                ('referencia_pago', models.CharField(blank=True, max_length=100, null=True, verbose_name='Referencia/Nº Transacción')),
                ('notas', models.TextField(blank=True, null=True, verbose_name='Notas del Pago')),
                ('banco', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_gimnasio.banco', verbose_name='Banco (Opcional)')),
                ('membresia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_gimnasio.membresia', verbose_name='Membresía Asociada')),
                ('metodo_pago', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app_gimnasio.metodopago', verbose_name='Método de Pago')),
                ('miembro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_gimnasio.miembro', verbose_name='Miembro que Paga')),
                ('registrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Registrado por Admin')),
            ],
            options={
                'verbose_name': 'Pago',
                'verbose_name_plural': 'Pagos',
            },
        ),
        migrations.CreateModel(
            name='RegistroAcceso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora_intento', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y Hora del Intento')),
                ('tipo_acceso', models.CharField(choices=[('Entrada', 'Entrada'), ('Salida', 'Salida')], max_length=10, verbose_name='Tipo de Acceso')),
                ('resultado_verificacion', models.CharField(choices=[('Permitido', 'Permitido'), ('Denegado - Vencido', 'Denegado - Vencido'), ('Denegado - No Encontrado', 'Denegado - No Encontrado'), ('Denegado - Sin Pago', 'Denegado - Sin Pago'), ('Denegado - Otro', 'Denegado - Otro')], max_length=30, verbose_name='Resultado')),
                ('punto_acceso', models.CharField(blank=True, max_length=50, null=True, verbose_name='Punto de Acceso')),
                ('miembro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_gimnasio.miembro', verbose_name='Miembro')),
            ],
            options={
                'verbose_name': 'Registro de Acceso',
                'verbose_name_plural': 'Registros de Acceso',
            },
        ),
        migrations.CreateModel(
            name='HorarioClase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.IntegerField(choices=[(0, 'Lunes'), (1, 'Martes'), (2, 'Miércoles'), (3, 'Jueves'), (4, 'Viernes'), (5, 'Sábado'), (6, 'Domingo')], verbose_name='Día de la Semana')),
                ('hora_inicio', models.TimeField(verbose_name='Hora de Inicio')),
                ('hora_fin', models.TimeField(verbose_name='Hora de Fin')),
                ('capacidad_maxima', models.PositiveIntegerField(blank=True, null=True, verbose_name='Capacidad Máxima')),
                ('activo', models.BooleanField(default=True, verbose_name='¿Activo?')),
                ('entrenador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_gimnasio.entrenador', verbose_name='Entrenador')),
                ('tipo_clase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_gimnasio.tipoclase', verbose_name='Tipo de Clase')),
            ],
            options={
                'verbose_name': 'Horario de Clase',
                'verbose_name_plural': 'Horarios de Clases',
            },
        ),
        migrations.CreateModel(
            name='AsignacionEntrenador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_asignacion', models.DateField(auto_now_add=True, verbose_name='Fecha de Asignación')),
                ('notas_asignacion', models.TextField(blank=True, null=True, verbose_name='Notas')),
                ('entrenador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_gimnasio.entrenador', verbose_name='Entrenador Asignado')),
                ('miembro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_gimnasio.miembro', verbose_name='Miembro')),
            ],
            options={
                'verbose_name': 'Asignación de Entrenador',
                'verbose_name_plural': 'Asignaciones de Entrenadores',
                'unique_together': {('miembro', 'entrenador')},
            },
        ),
    ]
