# Generated by Django 5.2 on 2025-04-19 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_gimnasio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='membresia',
            name='notas',
            field=models.TextField(blank=True, null=True, verbose_name='Notas Adicionales'),
        ),
    ]
