# Generated by Django 5.2 on 2025-04-19 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_gimnasio', '0002_membresia_notas'),
    ]

    operations = [
        migrations.AddField(
            model_name='membresia',
            name='renovada',
            field=models.BooleanField(default=False, verbose_name='¿Renovada?'),
        ),
    ]
